# CLUSTERING

Agrupar usuarios Twitter de acuerdo a su personalidad con K-means

In [2]:
# Ejercicio esta hecho sobre python 3.5, pero se puede usar python 2.7

# importando modulos que se van a usar

import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min

In [3]:
pathArchivos = input("Escriba el PATH directorio / carpeta de su archivo de analisis")

Escriba el PATH directorio / carpeta de su archivo de analisisC:\Users\lc.mojica639\Documents\Cientificas de Datos\Bootcamp\


In [4]:
pathArchivos

'C:\\Users\\lc.mojica639\\Documents\\Cientificas de Datos\\Bootcamp\\'

In [5]:
#importar archivo
dfAnalisis = pd.read_csv(pathArchivos + "analisis.csv")

In [6]:
dfAnalisis.head()

usuario         op         co         ex         ag         ne  \
0     3gerardpique  34.297953  28.148819  41.948819  29.370315   9.841575   
1  aguerosergiokun  44.986842  20.525865  37.938947  24.279098  10.362406   
2   albertochicote  41.733854  13.745417  38.999896  34.645521   8.836979   
3    AlejandroSanz  40.377154  15.377462  52.337538  31.082154   5.032231   
4   alfredocasero1  36.664677  19.642258  48.530806  31.138871   7.305968   

   wordcount  categoria  
0    37.0945          7  
1    78.7970          7  
2    49.2604          4  
3    80.4538          2  
4    47.0645          4

In [9]:
X = np.array(dfAnalisis[["op","ex","ag"]])
y = np.array(dfAnalisis['categoria'])
X.shape

(140, 3)

In [11]:
kmeans = KMeans(n_clusters=5).fit(X)
centroids = kmeans.cluster_centers_
print(centroids)

[[43.3644665  31.89755772 19.50586767]
 [35.90241306 47.56828232 33.58748762]
 [49.99285115 40.87133549 17.47411785]
 [59.25320707 31.29770653 15.9896352 ]
 [39.94672753 42.82349753 23.72594859]]


In [12]:
# Predicting the clusters
labels = kmeans.predict(X)
# Getting the cluster centers
C = kmeans.cluster_centers_
colores=['red','green','blue','cyan','yellow']
asignar=[]
for row in labels:
    asignar.append(colores[row])

In [13]:
copy =  pd.DataFrame()
copy['usuario']=dfAnalisis['usuario'].values
copy['categoria']=dfAnalisis['categoria'].values
copy['label'] = labels;
cantidadGrupo =  pd.DataFrame()
cantidadGrupo['color']=colores
cantidadGrupo['cantidad']=copy.groupby('label').size()
cantidadGrupo

color  cantidad
0     red        18
1   green        34
2    blue        41
3    cyan        15
4  yellow        32

In [14]:
group_referrer_index = copy['label'] ==0
group_referrals = copy[group_referrer_index]

diversidadGrupo =  pd.DataFrame()
diversidadGrupo['categoria']=[0,1,2,3,4,5,6,7,8,9]
diversidadGrupo['cantidad']=group_referrals.groupby('categoria').size()
diversidadGrupo

categoria  cantidad
0          0       NaN
1          1       6.0
2          2       3.0
3          3       1.0
4          4       1.0
5          5       NaN
6          6       1.0
7          7       1.0
8          8       5.0
9          9       NaN

In [15]:
#vemos el representante del grupo, el usuario cercano a su centroid
closest, _ = pairwise_distances_argmin_min(kmeans.cluster_centers_, X)
closest

array([123,  98,  21,  82,  64], dtype=int64)

In [16]:
users=dfAnalisis['usuario'].values
for row in closest:
    print(users[row])

SJP
maria_patino
carmenelectra
JudgeJudy
ierrejon


In [17]:
X_new = np.array([[45.92,57.74,15.66]]) #davidguetta
 
new_labels = kmeans.predict(X_new)
print(new_labels)

[2]
