# NumPy 

** NumPy: Librería de álgebra lineal para Python.**

NumPy es el paquete fundamental para la computación científica con Python. Contiene, entre otras cosas:
* un poderoso objeto de matrices N-dimensionales: arreglos numpy
* funciones sofisticadas (broadcast)
* herramientas para integrar código C/C ++ y Fortran
* funcionalidades útiles de álgebra lineal, transformada de Fourier, números aleatorios

Además de sus usos científicos obvios, NumPy también se puede usar como un contenedor multidimensional eficiente de datos genéricos. Se pueden definir tipos de datos arbitrarios. Esto permite a NumPy integrarse de manera rápida y sin problemas con una amplia variedad de bases de datos.

NumPy también es muy rápido (ya que usa librerías de lenguaje C). Para ver más información acerca de por qué usar Arreglos en lugar de Listas, ver [este post de StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## Instalación

**Se recomienda instalar Python usando la distribución Anaconda para asegurarse que todas las dependencias (como las librerías de álgebra lineal) se instalarán mediante el uso del comando "conda install". Si tiene Anaconda, instale NumPy simplemente escribiendo el siguiente comando en una terminal:**
    
    conda install numpy
    
**Si no tiene la distribución Anaconda, ejecute el comando "pip install numpy". Si no tiene éxito, ver: [la documentación oficial de Numpy para más instrucciones de instalación.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Una vez se haya instalado NumPy, se puede importar como una librería:

In [1]:
import numpy as np

** En este notebook trabajaremos con:**

* Arreglos NumPy: vectores, matrices
* Funciones para generar arreglos
* Generación de arreglos con números aleatorios
* Métodos y atributos de los arreglos


# Arreglos NumPy

Los arreglos de NumPy serán la principal funcionalidad que usaremos durante el curso. 

**Tipos de arreglos:**
* Vectores: 1-d
* Matrices: 2-d (aunque podrían tener una sola fila o una sola columna)



## Creación de Arreglos NumPy (Arrays)

### A partir de Listas de Python 

Podemos crear un Array conviertiendo una lista o lista de listas en un arreglo de NumPy:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Funciones para generar arreglos

Existen varias funciones para generar Arreglos:

## arange

Funciona de forma similar al método "range" de Python pero devuelve un arreglo.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## ceros y unos (zeros/ones)

Generan arreglos de ceros (zeros) y unos (ones).

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace
Retorna un vector (arreglo de una dimensión) desde un número (primer parámetro) hasta otro (segundo parámetro) separados entre si por la misma distancia. El número de elementos está determinado por el tercer parámetro.

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## eye

Crea una matriz identidad del tamaño indicado en el argumento.

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Generación de arreglos con números aleatorios

Numpy también ofrece varias maneras de crear arreglos de número aleatorios:


## rand
Crea un arreglo del tamaño dado y lo llena con una muestra aleatoria de números con una distribución uniforme en el rango ``[0, 1)``. Todos los números reales entre 0 y 1 tienen la misma probabilidad de ocurrencia.

Más info acerca de distribuciones de probabilidad en este [**enlace**](https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1b-statistical-methods/statistical-distributions). 

In [22]:
np.random.rand(2)

array([0.72497679, 0.95636389])

In [23]:
np.random.rand(5,5)

array([[0.76199148, 0.35674493, 0.9491814 , 0.1152271 , 0.47358251],
       [0.80232676, 0.8038509 , 0.14950969, 0.74766074, 0.13554409],
       [0.13459707, 0.19847067, 0.59933511, 0.00222104, 0.34465246],
       [0.22336613, 0.85292794, 0.59613678, 0.8489945 , 0.94459355],
       [0.46216894, 0.96819264, 0.72446796, 0.44847941, 0.96728438]])

In [24]:
np.random.rand(2,4)

array([[0.00927645, 0.18236634, 0.58224552, 0.71275921],
       [0.05334899, 0.44003855, 0.95646022, 0.10673537]])

## randn
Retorna un arreglo con una muestra de números aleatorios con una distribución normal (centrada en 0), a diferencia de rand cuya distribución es uniforme:

<img src="normal.jpg">

In [25]:
np.random.randn(2)

array([ 0.56873082, -0.95768916])

In [26]:
np.random.randn(4,5)

array([[ 1.75362898,  0.20171306,  0.39757462,  1.48849763, -2.23978373],
       [-0.90204315, -1.2199826 ,  0.5741995 , -0.71553256,  1.65827433],
       [-0.88923087, -1.79075329, -0.93453904,  0.13494435,  0.14022818],
       [-1.58081461,  1.25157478, -1.01333762, -0.53404218, -1.31811762]])

## randint
Retorna números enteros aleatorios desde el primer parámetro (inclusive) hasta el segundo parámetro (excluido). Si tiene un tercer argumento, éste será el número de elementos que tendrá el arreglo de enteros aleatorios que retorna.

In [27]:
np.random.randint(1,100)

27

In [28]:
np.random.randint(1,100,10)

array([ 6, 95, 32, 68, 94, 63, 10, 49, 91, 16])

In [29]:
# Ver todas las posibilidades escribiendo "np.random." y después TAB

# Métodos y atributos de los arreglos


In [30]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([30, 33,  1, 16, 44, 19, 47, 30, 39, 37])

## Reshape
Retorna un arreglo que contiene los mismos datos que el arreglo original pero con unas dimensiones nuevas.

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
# Debe contener el mismo número de elementos que el arreglo original. De lo contrario se produce un error como aquí:
arr.reshape(2, 5)


ValueError: cannot reshape array of size 25 into shape (2,5)

In [35]:
ranarr.reshape(5,2)

array([[30, 33],
       [ 1, 16],
       [44, 19],
       [47, 30],
       [39, 37]])

## max, min, argmax, argmin

Estos métodos son muy útiles para encontrar los valores máximos y mínimos en un arreglo. También, para encontrar los índices donde están ubicados mediante argmin/argmax.

In [37]:
ranarr

array([30, 33,  1, 16, 44, 19, 47, 30, 39, 37])

In [38]:
ranarr.max()

47

In [39]:
ranarr.argmax()

6

In [40]:
ranarr.min()

1

In [41]:
ranarr.argmin()

2

## Shape

Shape es un atributo de los arreglos (no es un método, se usa sin paréntesis). Devuelve las dimensiones del arreglo:

In [42]:
# Vector: 1-dimensión
arr.shape

(25,)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

In [ ]:
# Notese los dos corchetes: matriz
arr = arr.reshape(25,1)
arr

In [45]:
arr.shape

(5, 5)

## dtype

También es posible averiguar el tipo de dato del arreglo usando el atributo dtype:

In [46]:
arr.dtype

dtype('int32')

## Se puede importar la función que queramos
Para evitar escribir np.random todo el tiempo para acceder a diferentes funciones, se puede importar la función directamente.

In [47]:
from numpy.random import randint

In [48]:
randint(500,1000)

981